name: Deploy Flask API

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_KEY }}" > ~/.ssh/id_rsa

          # ðŸ”¥ Fix Windows CRLF â†’ Linux LF
          sed -i 's/\r$//' ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo Connected Successfully"

      - name: Deploy to VPS
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa \
            ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "
              cd ~/prac/practice &&
              git pull &&
              docker-compose down --remove-orphans &&
              docker rm -f \$(docker ps -aq) || true &&
              docker-compose up -d --build
            "
